image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- before: |
    nvm install
    nvm alias default node
    nvm use
  command: yarn

vscode:
  extensions:
    - Orta.vscode-jest@3.1.1:e5QDEGVUNAQFNn6OtB9Qmw==
