image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- before: |
    nvm install
    nvm alias default node
    nvm use
  command: yarn

vscode:
  extensions:
    - eamodio.gitlens@10.2.1:ZI2Sl3DHdJu4aG2wW92CQQ==
    - DavidAnson.vscode-markdownlint@0.36.3:rP8OhcezPp70k1tUGpNulw==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - esbenp.prettier-vscode@5.5.0:xcEnHt0vYXkhJ8IkBmNAuA==
    - Orta.vscode-jest@4.0.0-alpha.1:TuNngpN2TTsC/Ck1qhIwrg==