import { TextLineDto } from 'transliteration/domain/text-line'

export const moreLines: readonly TextLineDto[] = [
  {
    type: 'TextLine',
    lineNumber: {
      type: 'LineNumber',
      number: 10,
      hasPrime: false,
      prefixModifier: null,
      suffixModifier: null,
    },
    prefix: '10.',
    content: [
      {
        type: 'Word',
        value: 'šim',
        cleanValue: 'šim',
        uniqueLemma: [],
        normalized: false,
        language: 'AKKADIAN',
        lemmatizable: true,
        alignable: true,
        erasure: 'NONE',
        parts: [],
        enclosureType: [],
        alignment: null,
        variant: null,
        hasVariantAlignment: false,
        hasOmittedAlignment: false,
      },
      {
        type: 'ValueToken',
        value: '|',
        cleanValue: '|',
        enclosureType: [],
      },
      {
        type: 'Word',
        value: 'šim',
        cleanValue: 'šim',
        uniqueLemma: [],
        normalized: false,
        language: 'AKKADIAN',
        lemmatizable: true,
        alignable: true,
        erasure: 'NONE',
        parts: [],
        enclosureType: [],
        alignment: null,
        variant: null,
        hasVariantAlignment: false,
        hasOmittedAlignment: false,
      },
    ],
  },
  {
    type: 'TextLine',
    lineNumber: {
      type: 'LineNumber',
      number: 10,
      hasPrime: false,
      prefixModifier: null,
      suffixModifier: null,
    },
    prefix: '10.',
    content: [
      {
        type: 'UnknownNumberOfSigns',
        value: '...',
        cleanValue: '...',
        enclosureType: [],
      },
      {
        type: 'Word',
        value: '+ku',
        cleanValue: '+ku',
        uniqueLemma: [],
        normalized: false,
        language: 'AKKADIAN',
        lemmatizable: false,
        alignable: false,
        erasure: 'NONE',
        parts: [],
        enclosureType: [],
        alignment: null,
        variant: null,
        hasVariantAlignment: false,
        hasOmittedAlignment: false,
      },
      {
        type: 'LoneDeterminative',
        value: '{KA.G[A}',
        cleanValue: '{KA.GA}',
        uniqueLemma: [],
        normalized: false,
        language: 'AKKADIAN',
        lemmatizable: false,
        alignable: false,
        erasure: 'NONE',
        parts: [],
        enclosureType: [],
        alignment: null,
        variant: null,
        hasVariantAlignment: false,
        hasOmittedAlignment: false,
      },
      {
        type: 'UnknownNumberOfSigns',
        value: '...',
        cleanValue: '...',
        enclosureType: [],
      },
      {
        type: 'UnknownNumberOfSigns',
        value: '...',
        cleanValue: '...',
        enclosureType: [],
      },
      {
        type: 'Word',
        value: '.ku',
        cleanValue: '.ku',
        uniqueLemma: [],
        normalized: false,
        language: 'AKKADIAN',
        lemmatizable: false,
        alignable: false,
        erasure: 'NONE',
        parts: [],
        enclosureType: [],
        alignment: null,
        variant: null,
        hasVariantAlignment: false,
        hasOmittedAlignment: false,
      },
      {
        type: 'Word',
        value: 'x',
        cleanValue: 'x',
        uniqueLemma: [],
        normalized: false,
        language: 'AKKADIAN',
        lemmatizable: false,
        alignable: false,
        erasure: 'NONE',
        parts: [],
        enclosureType: [],
        alignment: null,
        variant: null,
        hasVariantAlignment: false,
        hasOmittedAlignment: false,
      },
    ],
  },
]
