import { Token } from 'transliteration/domain/token'

export const reconstructionTokens: Token[] = [
  {
    value: '%n',
    cleanValue: '%n',
    enclosureType: [],
    erasure: 'NONE',
    language: 'AKKADIAN',
    normalized: true,
    type: 'LanguageShift',
  },
  {
    value: 'kur-kur',
    cleanValue: 'kur-kur',
    enclosureType: [],
    erasure: 'NONE',
    lemmatizable: true,
    alignable: true,
    alignment: null,
    variant: null,
    uniqueLemma: [],
    normalized: true,
    language: 'AKKADIAN',
    parts: [
      {
        value: 'kur-kur',
        cleanValue: 'kur-kur',
        enclosureType: [],
        erasure: 'NONE',
        type: 'ValueToken',
      },
    ],
    modifiers: [],
    type: 'AkkadianWord',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
]

export const atfTokens: Token[] = [
  {
    type: 'Word',
    value: 'kur',
    parts: [],
    cleanValue: 'kur',
    uniqueLemma: [],
    normalized: false,
    language: 'AKKADIAN',
    lemmatizable: true,
    alignable: true,
    erasure: 'NONE',
    alignment: null,
    variant: null,
    enclosureType: [],
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    type: 'Word',
    value: 'ra',
    parts: [],
    cleanValue: 'ra',
    uniqueLemma: ['aklu I'],
    normalized: false,
    language: 'AKKADIAN',
    lemmatizable: true,
    alignable: true,
    erasure: 'NONE',
    alignment: 1,
    variant: {
      type: 'Word',
      value: 'ra',
      parts: [],
      cleanValue: 'ra',
      uniqueLemma: ['aklu I'],
      normalized: false,
      language: 'AKKADIAN',
      lemmatizable: true,
      alignable: true,
      erasure: 'NONE',
      alignment: null,
      variant: null,
      enclosureType: [],
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
    enclosureType: [],
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    value: '...',
    cleanValue: '...',
    enclosureType: [],
    erasure: 'NONE',
    type: 'UnknownNumberOfSigns',
  },
]
