import replaceSpecialCharacters from './replaceSpecialCharacters.js'

test.each([
  ['\\A', 'Ā'],
  ['\\a', 'ā'],
  ['\\E', 'Ē'],
  ['\\e', 'ē'],
  ['\\I', 'Ī'],
  ['\\i', 'ī'],
  ['\\U', 'Ū'],
  ['\\u', 'ū'],
  ['\\^A', 'Â'],
  ['\\^a', 'â'],
  ['\\^E', 'Ê'],
  ['\\^e', 'ê'],
  ['\\^I', 'Î'],
  ['\\^i', 'î'],
  ['\\^U', 'Û'],
  ['\\^u', 'û'],
  ['\\vS', 'Š'],
  ['\\vs', 'š'],
  ['\\S,', 'Ṣ'],
  ['\\s,', 'ṣ'],
  ['\\T', 'Ṭ'],
  ['\\t', 'ṭ'],
  ['\\\'', 'ʾ'],
  ['\\G', 'Ĝ'],
  ['\\g', 'ĝ'],
  ['\\1', '₁'],
  ['\\2', '₂'],
  ['\\3', '₃'],
  ['\\4', '₄'],
  ['\\5', '₅'],
  ['\\6', '₆'],
  ['\\7', '₇'],
  ['\\8', '₈'],
  ['\\9', '₉'],
  ['\\0', '₀'],
  ['\\x', 'ₓ'],
  ['\\r', '\\r'],
  [' ', ' '],
  ['\\s,u\\3-ru\\2-\\gul\\1\\0-t\\^u-lu-um', 'ṣu₃-ru₂-ĝul₁₀-tû-lu-um'],
  ['\\ta-\\ja-\\ru-\\li-\\tu-\\\'-um', 'ṭa-\\ja-\\ru-\\li-ṭu-ʾ-um']
])('%s filter', (userInput, expected) => {
  const newString = replaceSpecialCharacters(userInput)
  expect(newString).toEqual(expected)
})
