// flow-typed signature: 91d7e65327c3151c24f24153dfb132be
// flow-typed version: <<STUB>>/auth0-js_v^9.6.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0-js/build/auth0' {
  declare module.exports: any;
}

declare module 'auth0-js/build/auth0.min.esm' {
  declare module.exports: any;
}

declare module 'auth0-js/build/auth0.min' {
  declare module.exports: any;
}

declare module 'auth0-js/build/cordova-auth0-plugin' {
  declare module.exports: any;
}

declare module 'auth0-js/build/cordova-auth0-plugin.min' {
  declare module.exports: any;
}

declare module 'auth0-js/dist/auth0' {
  declare module.exports: any;
}

declare module 'auth0-js/dist/auth0.min.esm' {
  declare module.exports: any;
}

declare module 'auth0-js/dist/auth0.min' {
  declare module.exports: any;
}

declare module 'auth0-js/dist/cordova-auth0-plugin' {
  declare module.exports: any;
}

declare module 'auth0-js/dist/cordova-auth0-plugin.min' {
  declare module.exports: any;
}

declare module 'auth0-js/plugins/cordova' {
  declare module.exports: any;
}

declare module 'auth0-js/plugins/cordova/plugin-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/plugins/cordova/popup-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/authentication/db-connection' {
  declare module.exports: any;
}

declare module 'auth0-js/src/authentication' {
  declare module.exports: any;
}

declare module 'auth0-js/src/authentication/passwordless-authentication' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/assert' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/base64_url' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/error' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/iframe-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/object-assign' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/object' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/parameters-whitelist' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/plugins' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/popup-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/random' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/request-builder' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/response-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/ssodata' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage/cookie' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage/dummy' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage/handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/times' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/url' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/warn' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/window' {
  declare module.exports: any;
}

declare module 'auth0-js/src' {
  declare module.exports: any;
}

declare module 'auth0-js/src/management' {
  declare module.exports: any;
}

declare module 'auth0-js/src/version' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/cross-origin-authentication' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/hosted-pages' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/popup' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/redirect' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/silent-authentication-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/transaction-manager' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/username-password' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/web-message-handler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0-js/build/auth0.js' {
  declare module.exports: $Exports<'auth0-js/build/auth0'>;
}
declare module 'auth0-js/build/auth0.min.esm.js' {
  declare module.exports: $Exports<'auth0-js/build/auth0.min.esm'>;
}
declare module 'auth0-js/build/auth0.min.js' {
  declare module.exports: $Exports<'auth0-js/build/auth0.min'>;
}
declare module 'auth0-js/build/cordova-auth0-plugin.js' {
  declare module.exports: $Exports<'auth0-js/build/cordova-auth0-plugin'>;
}
declare module 'auth0-js/build/cordova-auth0-plugin.min.js' {
  declare module.exports: $Exports<'auth0-js/build/cordova-auth0-plugin.min'>;
}
declare module 'auth0-js/dist/auth0.js' {
  declare module.exports: $Exports<'auth0-js/dist/auth0'>;
}
declare module 'auth0-js/dist/auth0.min.esm.js' {
  declare module.exports: $Exports<'auth0-js/dist/auth0.min.esm'>;
}
declare module 'auth0-js/dist/auth0.min.js' {
  declare module.exports: $Exports<'auth0-js/dist/auth0.min'>;
}
declare module 'auth0-js/dist/cordova-auth0-plugin.js' {
  declare module.exports: $Exports<'auth0-js/dist/cordova-auth0-plugin'>;
}
declare module 'auth0-js/dist/cordova-auth0-plugin.min.js' {
  declare module.exports: $Exports<'auth0-js/dist/cordova-auth0-plugin.min'>;
}
declare module 'auth0-js/plugins/cordova/index' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova'>;
}
declare module 'auth0-js/plugins/cordova/index.js' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova'>;
}
declare module 'auth0-js/plugins/cordova/plugin-handler.js' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova/plugin-handler'>;
}
declare module 'auth0-js/plugins/cordova/popup-handler.js' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova/popup-handler'>;
}
declare module 'auth0-js/src/authentication/db-connection.js' {
  declare module.exports: $Exports<'auth0-js/src/authentication/db-connection'>;
}
declare module 'auth0-js/src/authentication/index' {
  declare module.exports: $Exports<'auth0-js/src/authentication'>;
}
declare module 'auth0-js/src/authentication/index.js' {
  declare module.exports: $Exports<'auth0-js/src/authentication'>;
}
declare module 'auth0-js/src/authentication/passwordless-authentication.js' {
  declare module.exports: $Exports<'auth0-js/src/authentication/passwordless-authentication'>;
}
declare module 'auth0-js/src/helper/assert.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/assert'>;
}
declare module 'auth0-js/src/helper/base64_url.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/base64_url'>;
}
declare module 'auth0-js/src/helper/error.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/error'>;
}
declare module 'auth0-js/src/helper/iframe-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/iframe-handler'>;
}
declare module 'auth0-js/src/helper/object-assign.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/object-assign'>;
}
declare module 'auth0-js/src/helper/object.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/object'>;
}
declare module 'auth0-js/src/helper/parameters-whitelist.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/parameters-whitelist'>;
}
declare module 'auth0-js/src/helper/plugins.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/plugins'>;
}
declare module 'auth0-js/src/helper/popup-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/popup-handler'>;
}
declare module 'auth0-js/src/helper/random.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/random'>;
}
declare module 'auth0-js/src/helper/request-builder.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/request-builder'>;
}
declare module 'auth0-js/src/helper/response-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/response-handler'>;
}
declare module 'auth0-js/src/helper/ssodata.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/ssodata'>;
}
declare module 'auth0-js/src/helper/storage.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage'>;
}
declare module 'auth0-js/src/helper/storage/cookie.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage/cookie'>;
}
declare module 'auth0-js/src/helper/storage/dummy.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage/dummy'>;
}
declare module 'auth0-js/src/helper/storage/handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage/handler'>;
}
declare module 'auth0-js/src/helper/times.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/times'>;
}
declare module 'auth0-js/src/helper/url.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/url'>;
}
declare module 'auth0-js/src/helper/warn.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/warn'>;
}
declare module 'auth0-js/src/helper/window.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/window'>;
}
declare module 'auth0-js/src/index' {
  declare module.exports: $Exports<'auth0-js/src'>;
}
declare module 'auth0-js/src/index.js' {
  declare module.exports: $Exports<'auth0-js/src'>;
}
declare module 'auth0-js/src/management/index' {
  declare module.exports: $Exports<'auth0-js/src/management'>;
}
declare module 'auth0-js/src/management/index.js' {
  declare module.exports: $Exports<'auth0-js/src/management'>;
}
declare module 'auth0-js/src/version.js' {
  declare module.exports: $Exports<'auth0-js/src/version'>;
}
declare module 'auth0-js/src/web-auth/cross-origin-authentication.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/cross-origin-authentication'>;
}
declare module 'auth0-js/src/web-auth/hosted-pages.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/hosted-pages'>;
}
declare module 'auth0-js/src/web-auth/index' {
  declare module.exports: $Exports<'auth0-js/src/web-auth'>;
}
declare module 'auth0-js/src/web-auth/index.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth'>;
}
declare module 'auth0-js/src/web-auth/popup.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/popup'>;
}
declare module 'auth0-js/src/web-auth/redirect.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/redirect'>;
}
declare module 'auth0-js/src/web-auth/silent-authentication-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/silent-authentication-handler'>;
}
declare module 'auth0-js/src/web-auth/transaction-manager.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/transaction-manager'>;
}
declare module 'auth0-js/src/web-auth/username-password.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/username-password'>;
}
declare module 'auth0-js/src/web-auth/web-message-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/web-message-handler'>;
}
