// flow-typed signature: 4634cd977cde15a7f60f6f7f14463d11
// flow-typed version: <<STUB>>/citation-js_v^0.4.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'citation-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'citation-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'citation-js/bin/cmd' {
  declare module.exports: any;
}

declare module 'citation-js/build/citation' {
  declare module.exports: any;
}

declare module 'citation-js/build/citation.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'citation-js/bin/cmd.js' {
  declare module.exports: $Exports<'citation-js/bin/cmd'>;
}
declare module 'citation-js/build/citation.js' {
  declare module.exports: $Exports<'citation-js/build/citation'>;
}
declare module 'citation-js/build/citation.min.js' {
  declare module.exports: $Exports<'citation-js/build/citation.min'>;
}
declare module 'citation-js/index' {
  declare module.exports: $Exports<'citation-js'>;
}
declare module 'citation-js/index.js' {
  declare module.exports: $Exports<'citation-js'>;
}
