// flow-typed signature: 52852ea3c9f8b110598cdc532e8f6aea
// flow-typed version: <<STUB>>/factory-girl_v^5.0.2/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'factory-girl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'factory-girl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'factory-girl/browser' {
  declare module.exports: any;
}

declare module 'factory-girl/index.es6' {
  declare module.exports: any;
}

declare module 'factory-girl/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'factory-girl/browser.js' {
  declare module.exports: $Exports<'factory-girl/browser'>;
}
declare module 'factory-girl/index.es6.js' {
  declare module.exports: $Exports<'factory-girl/index.es6'>;
}
declare module 'factory-girl/index' {
  declare module.exports: $Exports<'factory-girl'>;
}
declare module 'factory-girl/index.js' {
  declare module.exports: $Exports<'factory-girl'>;
}
declare module 'factory-girl/index.umd.js' {
  declare module.exports: $Exports<'factory-girl/index.umd'>;
}
