// flow-typed signature: 1fbae22a15d76c9e842774618f82063b
// flow-typed version: <<STUB>>/react-bootstrap_v^1.0.0-beta.9/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap/AbstractNav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/AbstractNavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/AccordionCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/AccordionContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/AccordionToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Card' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CardColumns' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CardContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CardDeck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CardGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CardImg' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CloseButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Container' {
  declare module.exports: any;
}

declare module 'react-bootstrap/dist/react-bootstrap' {
  declare module.exports: any;
}

declare module 'react-bootstrap/dist/react-bootstrap.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AbstractNav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AbstractNavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AccordionCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AccordionContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AccordionToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Card' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardColumns' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardDeck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardImg' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CloseButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Container' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Feedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Figure' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FigureCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FigureImage' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormCheck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormCheckInput' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormCheckLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormText' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavLink' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SelectableContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Spinner' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/test/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Toast' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToastBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToastContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToastHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/BootstrapModalManager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/createWithBsPrefix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/divWithClassName' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/ElementChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/triggerBrowserReflow' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Feedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Figure' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FigureCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FigureImage' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormCheck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormCheckInput' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormCheckLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormText' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavLink' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SelectableContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Spinner' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/test/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Toast' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ToastBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ToastContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ToastHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/utils/BootstrapModalManager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/utils/createWithBsPrefix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/utils/divWithClassName' {
  declare module.exports: any;
}

declare module 'react-bootstrap/utils/ElementChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/utils/triggerBrowserReflow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap/AbstractNav.js' {
  declare module.exports: $Exports<'react-bootstrap/AbstractNav'>;
}
declare module 'react-bootstrap/AbstractNavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/AbstractNavItem'>;
}
declare module 'react-bootstrap/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/Accordion'>;
}
declare module 'react-bootstrap/AccordionCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/AccordionCollapse'>;
}
declare module 'react-bootstrap/AccordionContext.js' {
  declare module.exports: $Exports<'react-bootstrap/AccordionContext'>;
}
declare module 'react-bootstrap/AccordionToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/AccordionToggle'>;
}
declare module 'react-bootstrap/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/Alert'>;
}
declare module 'react-bootstrap/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/Badge'>;
}
declare module 'react-bootstrap/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/Breadcrumb'>;
}
declare module 'react-bootstrap/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/BreadcrumbItem'>;
}
declare module 'react-bootstrap/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/Button'>;
}
declare module 'react-bootstrap/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ButtonGroup'>;
}
declare module 'react-bootstrap/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/ButtonToolbar'>;
}
declare module 'react-bootstrap/Card.js' {
  declare module.exports: $Exports<'react-bootstrap/Card'>;
}
declare module 'react-bootstrap/CardColumns.js' {
  declare module.exports: $Exports<'react-bootstrap/CardColumns'>;
}
declare module 'react-bootstrap/CardContext.js' {
  declare module.exports: $Exports<'react-bootstrap/CardContext'>;
}
declare module 'react-bootstrap/CardDeck.js' {
  declare module.exports: $Exports<'react-bootstrap/CardDeck'>;
}
declare module 'react-bootstrap/CardGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/CardGroup'>;
}
declare module 'react-bootstrap/CardImg.js' {
  declare module.exports: $Exports<'react-bootstrap/CardImg'>;
}
declare module 'react-bootstrap/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/Carousel'>;
}
declare module 'react-bootstrap/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/CarouselCaption'>;
}
declare module 'react-bootstrap/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/CarouselItem'>;
}
declare module 'react-bootstrap/CloseButton.js' {
  declare module.exports: $Exports<'react-bootstrap/CloseButton'>;
}
declare module 'react-bootstrap/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/Col'>;
}
declare module 'react-bootstrap/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/Collapse'>;
}
declare module 'react-bootstrap/Container.js' {
  declare module.exports: $Exports<'react-bootstrap/Container'>;
}
declare module 'react-bootstrap/dist/react-bootstrap.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap'>;
}
declare module 'react-bootstrap/dist/react-bootstrap.min.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap.min'>;
}
declare module 'react-bootstrap/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/Dropdown'>;
}
declare module 'react-bootstrap/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownButton'>;
}
declare module 'react-bootstrap/DropdownItem.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownItem'>;
}
declare module 'react-bootstrap/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownMenu'>;
}
declare module 'react-bootstrap/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownToggle'>;
}
declare module 'react-bootstrap/es/AbstractNav.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AbstractNav'>;
}
declare module 'react-bootstrap/es/AbstractNavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AbstractNavItem'>;
}
declare module 'react-bootstrap/es/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Accordion'>;
}
declare module 'react-bootstrap/es/AccordionCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AccordionCollapse'>;
}
declare module 'react-bootstrap/es/AccordionContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AccordionContext'>;
}
declare module 'react-bootstrap/es/AccordionToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AccordionToggle'>;
}
declare module 'react-bootstrap/es/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Alert'>;
}
declare module 'react-bootstrap/es/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Badge'>;
}
declare module 'react-bootstrap/es/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Breadcrumb'>;
}
declare module 'react-bootstrap/es/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/BreadcrumbItem'>;
}
declare module 'react-bootstrap/es/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Button'>;
}
declare module 'react-bootstrap/es/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ButtonGroup'>;
}
declare module 'react-bootstrap/es/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ButtonToolbar'>;
}
declare module 'react-bootstrap/es/Card.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Card'>;
}
declare module 'react-bootstrap/es/CardColumns.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardColumns'>;
}
declare module 'react-bootstrap/es/CardContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardContext'>;
}
declare module 'react-bootstrap/es/CardDeck.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardDeck'>;
}
declare module 'react-bootstrap/es/CardGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardGroup'>;
}
declare module 'react-bootstrap/es/CardImg.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardImg'>;
}
declare module 'react-bootstrap/es/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Carousel'>;
}
declare module 'react-bootstrap/es/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CarouselCaption'>;
}
declare module 'react-bootstrap/es/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CarouselItem'>;
}
declare module 'react-bootstrap/es/CloseButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CloseButton'>;
}
declare module 'react-bootstrap/es/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Col'>;
}
declare module 'react-bootstrap/es/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Collapse'>;
}
declare module 'react-bootstrap/es/Container.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Container'>;
}
declare module 'react-bootstrap/es/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Dropdown'>;
}
declare module 'react-bootstrap/es/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownButton'>;
}
declare module 'react-bootstrap/es/DropdownItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownItem'>;
}
declare module 'react-bootstrap/es/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownMenu'>;
}
declare module 'react-bootstrap/es/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownToggle'>;
}
declare module 'react-bootstrap/es/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Fade'>;
}
declare module 'react-bootstrap/es/Feedback.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Feedback'>;
}
declare module 'react-bootstrap/es/Figure.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Figure'>;
}
declare module 'react-bootstrap/es/FigureCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FigureCaption'>;
}
declare module 'react-bootstrap/es/FigureImage.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FigureImage'>;
}
declare module 'react-bootstrap/es/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Form'>;
}
declare module 'react-bootstrap/es/FormCheck.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormCheck'>;
}
declare module 'react-bootstrap/es/FormCheckInput.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormCheckInput'>;
}
declare module 'react-bootstrap/es/FormCheckLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormCheckLabel'>;
}
declare module 'react-bootstrap/es/FormContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormContext'>;
}
declare module 'react-bootstrap/es/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormControl'>;
}
declare module 'react-bootstrap/es/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormGroup'>;
}
declare module 'react-bootstrap/es/FormLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormLabel'>;
}
declare module 'react-bootstrap/es/FormText.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormText'>;
}
declare module 'react-bootstrap/es/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Image'>;
}
declare module 'react-bootstrap/es/index' {
  declare module.exports: $Exports<'react-bootstrap/es'>;
}
declare module 'react-bootstrap/es/index.js' {
  declare module.exports: $Exports<'react-bootstrap/es'>;
}
declare module 'react-bootstrap/es/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/InputGroup'>;
}
declare module 'react-bootstrap/es/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Jumbotron'>;
}
declare module 'react-bootstrap/es/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ListGroup'>;
}
declare module 'react-bootstrap/es/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ListGroupItem'>;
}
declare module 'react-bootstrap/es/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Media'>;
}
declare module 'react-bootstrap/es/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Modal'>;
}
declare module 'react-bootstrap/es/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalBody'>;
}
declare module 'react-bootstrap/es/ModalContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalContext'>;
}
declare module 'react-bootstrap/es/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalDialog'>;
}
declare module 'react-bootstrap/es/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalFooter'>;
}
declare module 'react-bootstrap/es/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalHeader'>;
}
declare module 'react-bootstrap/es/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalTitle'>;
}
declare module 'react-bootstrap/es/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Nav'>;
}
declare module 'react-bootstrap/es/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Navbar'>;
}
declare module 'react-bootstrap/es/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarBrand'>;
}
declare module 'react-bootstrap/es/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarCollapse'>;
}
declare module 'react-bootstrap/es/NavbarContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarContext'>;
}
declare module 'react-bootstrap/es/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarToggle'>;
}
declare module 'react-bootstrap/es/NavContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavContext'>;
}
declare module 'react-bootstrap/es/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavDropdown'>;
}
declare module 'react-bootstrap/es/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavItem'>;
}
declare module 'react-bootstrap/es/NavLink.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavLink'>;
}
declare module 'react-bootstrap/es/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Overlay'>;
}
declare module 'react-bootstrap/es/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/es/OverlayTrigger'>;
}
declare module 'react-bootstrap/es/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PageItem'>;
}
declare module 'react-bootstrap/es/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Pagination'>;
}
declare module 'react-bootstrap/es/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Popover'>;
}
declare module 'react-bootstrap/es/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ProgressBar'>;
}
declare module 'react-bootstrap/es/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/es/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Row'>;
}
declare module 'react-bootstrap/es/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SafeAnchor'>;
}
declare module 'react-bootstrap/es/SelectableContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SelectableContext'>;
}
declare module 'react-bootstrap/es/Spinner.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Spinner'>;
}
declare module 'react-bootstrap/es/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SplitButton'>;
}
declare module 'react-bootstrap/es/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tab'>;
}
declare module 'react-bootstrap/es/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContainer'>;
}
declare module 'react-bootstrap/es/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContent'>;
}
declare module 'react-bootstrap/es/TabContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContext'>;
}
declare module 'react-bootstrap/es/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Table'>;
}
declare module 'react-bootstrap/es/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabPane'>;
}
declare module 'react-bootstrap/es/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tabs'>;
}
declare module 'react-bootstrap/es/test/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/test/ButtonGroup'>;
}
declare module 'react-bootstrap/es/ThemeProvider.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ThemeProvider'>;
}
declare module 'react-bootstrap/es/Toast.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Toast'>;
}
declare module 'react-bootstrap/es/ToastBody.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToastBody'>;
}
declare module 'react-bootstrap/es/ToastContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToastContext'>;
}
declare module 'react-bootstrap/es/ToastHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToastHeader'>;
}
declare module 'react-bootstrap/es/ToggleButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToggleButton'>;
}
declare module 'react-bootstrap/es/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToggleButtonGroup'>;
}
declare module 'react-bootstrap/es/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tooltip'>;
}
declare module 'react-bootstrap/es/utils/BootstrapModalManager.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/BootstrapModalManager'>;
}
declare module 'react-bootstrap/es/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/es/utils/createWithBsPrefix.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/createWithBsPrefix'>;
}
declare module 'react-bootstrap/es/utils/divWithClassName.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/divWithClassName'>;
}
declare module 'react-bootstrap/es/utils/ElementChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/ElementChildren'>;
}
declare module 'react-bootstrap/es/utils/triggerBrowserReflow.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/triggerBrowserReflow'>;
}
declare module 'react-bootstrap/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/Fade'>;
}
declare module 'react-bootstrap/Feedback.js' {
  declare module.exports: $Exports<'react-bootstrap/Feedback'>;
}
declare module 'react-bootstrap/Figure.js' {
  declare module.exports: $Exports<'react-bootstrap/Figure'>;
}
declare module 'react-bootstrap/FigureCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/FigureCaption'>;
}
declare module 'react-bootstrap/FigureImage.js' {
  declare module.exports: $Exports<'react-bootstrap/FigureImage'>;
}
declare module 'react-bootstrap/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/Form'>;
}
declare module 'react-bootstrap/FormCheck.js' {
  declare module.exports: $Exports<'react-bootstrap/FormCheck'>;
}
declare module 'react-bootstrap/FormCheckInput.js' {
  declare module.exports: $Exports<'react-bootstrap/FormCheckInput'>;
}
declare module 'react-bootstrap/FormCheckLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/FormCheckLabel'>;
}
declare module 'react-bootstrap/FormContext.js' {
  declare module.exports: $Exports<'react-bootstrap/FormContext'>;
}
declare module 'react-bootstrap/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControl'>;
}
declare module 'react-bootstrap/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/FormGroup'>;
}
declare module 'react-bootstrap/FormLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/FormLabel'>;
}
declare module 'react-bootstrap/FormText.js' {
  declare module.exports: $Exports<'react-bootstrap/FormText'>;
}
declare module 'react-bootstrap/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/Image'>;
}
declare module 'react-bootstrap/index' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/index.js' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroup'>;
}
declare module 'react-bootstrap/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/Jumbotron'>;
}
declare module 'react-bootstrap/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ListGroup'>;
}
declare module 'react-bootstrap/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/ListGroupItem'>;
}
declare module 'react-bootstrap/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/Media'>;
}
declare module 'react-bootstrap/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/Modal'>;
}
declare module 'react-bootstrap/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalBody'>;
}
declare module 'react-bootstrap/ModalContext.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalContext'>;
}
declare module 'react-bootstrap/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalDialog'>;
}
declare module 'react-bootstrap/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalFooter'>;
}
declare module 'react-bootstrap/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalHeader'>;
}
declare module 'react-bootstrap/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalTitle'>;
}
declare module 'react-bootstrap/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/Nav'>;
}
declare module 'react-bootstrap/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/Navbar'>;
}
declare module 'react-bootstrap/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarBrand'>;
}
declare module 'react-bootstrap/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarCollapse'>;
}
declare module 'react-bootstrap/NavbarContext.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarContext'>;
}
declare module 'react-bootstrap/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarToggle'>;
}
declare module 'react-bootstrap/NavContext.js' {
  declare module.exports: $Exports<'react-bootstrap/NavContext'>;
}
declare module 'react-bootstrap/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/NavDropdown'>;
}
declare module 'react-bootstrap/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/NavItem'>;
}
declare module 'react-bootstrap/NavLink.js' {
  declare module.exports: $Exports<'react-bootstrap/NavLink'>;
}
declare module 'react-bootstrap/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/Overlay'>;
}
declare module 'react-bootstrap/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/OverlayTrigger'>;
}
declare module 'react-bootstrap/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/PageItem'>;
}
declare module 'react-bootstrap/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/Pagination'>;
}
declare module 'react-bootstrap/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/Popover'>;
}
declare module 'react-bootstrap/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/ProgressBar'>;
}
declare module 'react-bootstrap/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/Row'>;
}
declare module 'react-bootstrap/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/SafeAnchor'>;
}
declare module 'react-bootstrap/SelectableContext.js' {
  declare module.exports: $Exports<'react-bootstrap/SelectableContext'>;
}
declare module 'react-bootstrap/Spinner.js' {
  declare module.exports: $Exports<'react-bootstrap/Spinner'>;
}
declare module 'react-bootstrap/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/SplitButton'>;
}
declare module 'react-bootstrap/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/Tab'>;
}
declare module 'react-bootstrap/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContainer'>;
}
declare module 'react-bootstrap/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContent'>;
}
declare module 'react-bootstrap/TabContext.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContext'>;
}
declare module 'react-bootstrap/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/Table'>;
}
declare module 'react-bootstrap/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/TabPane'>;
}
declare module 'react-bootstrap/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/Tabs'>;
}
declare module 'react-bootstrap/test/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/test/ButtonGroup'>;
}
declare module 'react-bootstrap/ThemeProvider.js' {
  declare module.exports: $Exports<'react-bootstrap/ThemeProvider'>;
}
declare module 'react-bootstrap/Toast.js' {
  declare module.exports: $Exports<'react-bootstrap/Toast'>;
}
declare module 'react-bootstrap/ToastBody.js' {
  declare module.exports: $Exports<'react-bootstrap/ToastBody'>;
}
declare module 'react-bootstrap/ToastContext.js' {
  declare module.exports: $Exports<'react-bootstrap/ToastContext'>;
}
declare module 'react-bootstrap/ToastHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/ToastHeader'>;
}
declare module 'react-bootstrap/ToggleButton.js' {
  declare module.exports: $Exports<'react-bootstrap/ToggleButton'>;
}
declare module 'react-bootstrap/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ToggleButtonGroup'>;
}
declare module 'react-bootstrap/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/Tooltip'>;
}
declare module 'react-bootstrap/utils/BootstrapModalManager.js' {
  declare module.exports: $Exports<'react-bootstrap/utils/BootstrapModalManager'>;
}
declare module 'react-bootstrap/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/utils/createWithBsPrefix.js' {
  declare module.exports: $Exports<'react-bootstrap/utils/createWithBsPrefix'>;
}
declare module 'react-bootstrap/utils/divWithClassName.js' {
  declare module.exports: $Exports<'react-bootstrap/utils/divWithClassName'>;
}
declare module 'react-bootstrap/utils/ElementChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/utils/ElementChildren'>;
}
declare module 'react-bootstrap/utils/triggerBrowserReflow.js' {
  declare module.exports: $Exports<'react-bootstrap/utils/triggerBrowserReflow'>;
}
