import { TextLine } from 'transliteration/domain/text-line'

const line6 = new TextLine({
  prefix: '3.',
  content: [
    {
      enclosureType: [],
      cleanValue: '1@v',
      value: '1@v#*',
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: true,
      alignable: true,
      uniqueLemma: [],
      erasure: 'NONE',
      alignment: null,
      variant: null,
      parts: [
        {
          enclosureType: [],
          cleanValue: '1@v',
          value: '1@v#*',
          name: '1',
          nameParts: [
            {
              enclosureType: [],
              cleanValue: '1',
              value: '1',
              type: 'ValueToken',
            },
          ],
          subIndex: 1,
          modifiers: ['@v'],
          flags: ['#', '*'],
          sign: null,
          type: 'Number',
        },
      ],
      type: 'Word',
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
    {
      enclosureType: [],
      cleanValue: 'x',
      value: 'x#!',
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: false,
      alignable: false,
      uniqueLemma: [],
      erasure: 'NONE',
      alignment: null,
      variant: null,
      parts: [
        {
          enclosureType: [],
          cleanValue: 'x',
          value: 'x#!',
          flags: ['#', '!'],
          type: 'UnclearSign',
        },
      ],
      type: 'Word',
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
    {
      enclosureType: [],
      cleanValue: 'X',
      value: 'X#?',
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: false,
      alignable: false,
      uniqueLemma: [],
      erasure: 'NONE',
      alignment: null,
      variant: null,
      parts: [
        {
          enclosureType: [],
          cleanValue: 'X',
          value: 'X#?',
          flags: ['#', '?'],
          type: 'UnidentifiedSign',
        },
      ],
      type: 'Word',
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
    {
      enclosureType: [],
      cleanValue: '::@v@44',
      value: '::@v@44?#',
      divider: '::',
      modifiers: ['@v', '@44'],
      flags: ['?', '#'],
      type: 'Divider',
    },
    {
      enclosureType: [],
      cleanValue: '|',
      value: '|',
      type: 'LineBreak',
    },
    {
      enclosureType: [],
      cleanValue: 'x',
      value: '[(x)',
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: false,
      alignable: false,
      uniqueLemma: [],
      erasure: 'NONE',
      alignment: null,
      variant: null,
      parts: [
        {
          enclosureType: [],
          cleanValue: '',
          value: '[',
          side: 'LEFT',
          type: 'BrokenAway',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '',
          value: '(',
          side: 'LEFT',
          type: 'PerhapsBrokenAway',
        },
        {
          enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
          cleanValue: 'x',
          value: 'x',
          flags: [],
          type: 'UnclearSign',
        },
        {
          enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
          cleanValue: '',
          value: ')',
          side: 'RIGHT',
          type: 'PerhapsBrokenAway',
        },
      ],
      type: 'Word',
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
    {
      enclosureType: ['BROKEN_AWAY'],
      cleanValue: 'x',
      value: 'x]',
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: false,
      alignable: false,
      uniqueLemma: [],
      erasure: 'NONE',
      alignment: null,
      variant: null,
      parts: [
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: 'x',
          value: 'x',
          flags: [],
          type: 'UnclearSign',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '',
          value: ']',
          side: 'RIGHT',
          type: 'BrokenAway',
        },
      ],
      type: 'Word',
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
  ],
  lineNumber: {
    number: 3,
    hasPrime: false,
    prefixModifier: null,
    suffixModifier: null,
    type: 'LineNumber',
  },
  type: 'TextLine',
})

export default line6
