import { Token } from 'transliteration/domain/token'

export const line12ClosingTokens: Token[] = [
  {
    enclosureType: [],
    cleanValue: 'kur',
    value: 'kur',
    language: 'EMESAL',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: 'KUR{D}',
    value: 'KUR{D}',
    language: 'EMESAL',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'KUR',
        value: 'KUR',
        name: 'KUR',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'KUR',
            value: 'KUR',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        surrogate: [],
        type: 'Logogram',
      },
      {
        enclosureType: [],
        cleanValue: '{D}',
        value: '{D}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'D',
            value: 'D',
            name: 'D',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'D',
                value: 'D',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            surrogate: [],
            type: 'Logogram',
          },
        ],
        type: 'Determinative',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '%akk',
    value: '%akk',
    language: 'AKKADIAN',
    normalized: false,
    type: 'LanguageShift',
  },
  {
    enclosureType: [],
    cleanValue: 'kur',
    value: 'kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
]
