import { Token } from 'transliteration/domain/token'

export const line15EarlyTokens: Token[] = [
  {
    enclosureType: ['REMOVAL'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur>>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['REMOVAL'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['REMOVAL'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['REMOVAL'],
        cleanValue: '',
        value: '>>',
        side: 'RIGHT',
        type: 'Removal',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '',
    value: '{(',
    side: 'LEFT',
    type: 'DocumentOrientedGloss',
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    erasure: 'NONE',
    cleanValue: 'kur(KUR)',
    value: '<kur(KUR)',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '',
        value: '<',
        side: 'LEFT',
        type: 'AccidentalOmission',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'ACCIDENTAL_OMISSION'],
        cleanValue: 'kur(KUR)',
        value: 'kur(KUR)',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'ACCIDENTAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: {
          enclosureType: [],
          cleanValue: 'KUR',
          value: 'KUR',
          name: 'KUR',
          modifiers: [],
          flags: [],
          type: 'Grapheme',
        },
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'ACCIDENTAL_OMISSION'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'ACCIDENTAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'ACCIDENTAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'ACCIDENTAL_OMISSION'],
        cleanValue: '',
        value: '>',
        side: 'RIGHT',
        type: 'AccidentalOmission',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: '<(kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '',
        value: '<(',
        side: 'LEFT',
        type: 'IntentionalOmission',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'INTENTIONAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'INTENTIONAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
]
