import { Token } from 'transliteration/domain/token'

export const line15OpeningTokens: Token[] = [
  {
    enclosureType: [],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: '<kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '',
        value: '<',
        side: 'LEFT',
        type: 'AccidentalOmission',
      },
      {
        enclosureType: ['ACCIDENTAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['ACCIDENTAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['ACCIDENTAL_OMISSION'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['ACCIDENTAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['ACCIDENTAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['ACCIDENTAL_OMISSION'],
        cleanValue: '',
        value: '>',
        side: 'RIGHT',
        type: 'AccidentalOmission',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: '<(kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '',
        value: '<(',
        side: 'LEFT',
        type: 'IntentionalOmission',
      },
      {
        enclosureType: ['INTENTIONAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['INTENTIONAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['INTENTIONAL_OMISSION'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur)>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['INTENTIONAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['INTENTIONAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['INTENTIONAL_OMISSION'],
        cleanValue: '',
        value: ')>',
        side: 'RIGHT',
        type: 'IntentionalOmission',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: '<<kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '',
        value: '<<',
        side: 'LEFT',
        type: 'Removal',
      },
      {
        enclosureType: ['REMOVAL'],

        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['REMOVAL'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
]
