import { Token } from 'transliteration/domain/token'

export const line10ClosingTokens: Token[] = [
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: 'kur{+kur-RA}',
    value: 'kur{+k[ur]-RA}',
    language: 'EMESAL',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '{+kur-RA}',
        value: '{+k[ur]-RA}',
        parts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'kur',
            value: 'k[ur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
                cleanValue: 'k',
                value: 'k',
                type: 'ValueToken',
              },
              {
                enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
                cleanValue: '',
                value: '[',
                side: 'LEFT',
                type: 'BrokenAway',
              },
              {
                enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'BROKEN_AWAY'],
                cleanValue: 'ur',
                value: 'ur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'BROKEN_AWAY'],
            cleanValue: '',
            value: ']',
            side: 'RIGHT',
            type: 'BrokenAway',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: '-',
            value: '-',
            type: 'Joiner',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'RA',
            value: 'RA',
            name: 'RA',
            nameParts: [
              {
                enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
                cleanValue: 'RA',
                value: 'RA',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            surrogate: [],
            type: 'Logogram',
          },
        ],
        type: 'PhoneticGloss',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: '{kur}kur₂',
    value: '{kur}kur₂',
    language: 'EMESAL',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '{kur}',
        value: '{kur}',
        parts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Determinative',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: 'kur₂',
        value: 'kur₂',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 2,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: '',
    value: ')}',
    side: 'RIGHT',
    type: 'DocumentOrientedGloss',
  },
]
