import { Token } from 'transliteration/domain/token'

export const line15ClosingTokens: Token[] = [
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    erasure: 'NONE',
    cleanValue: 'KUR<(kur-kur)>',
    value: 'KUR<(kur-kur)>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],

        cleanValue: 'KUR<(kur-kur)>',
        value: 'KUR<(kur-kur)>',
        name: 'KUR',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'KUR',
            value: 'KUR',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        surrogate: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
          {
            enclosureType: [],
            cleanValue: '-',
            value: '-',
            type: 'Joiner',
          },
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Logogram',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: '',
    value: ')}',
    side: 'RIGHT',
    type: 'DocumentOrientedGloss',
  },
]
