import { Token } from 'transliteration/domain/token'

export const line15LateTokens: Token[] = [
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'INTENTIONAL_OMISSION'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur)>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'INTENTIONAL_OMISSION'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'INTENTIONAL_OMISSION'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'INTENTIONAL_OMISSION'],
        cleanValue: '',
        value: ')>',
        side: 'RIGHT',
        type: 'IntentionalOmission',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: '<<kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '',
        value: '<<',
        side: 'LEFT',
        type: 'Removal',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'REMOVAL'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'REMOVAL'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'REMOVAL'],
    erasure: 'NONE',
    cleanValue: 'kur',
    value: 'kur>>',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'REMOVAL'],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'REMOVAL'],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'REMOVAL'],
        cleanValue: '',
        value: '>>',
        side: 'RIGHT',
        type: 'Removal',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: '',
    value: ')}',
    side: 'RIGHT',
    type: 'DocumentOrientedGloss',
  },
  {
    enclosureType: [],
    cleanValue: '',
    value: '{(',
    side: 'LEFT',
    type: 'DocumentOrientedGloss',
  },
]
