import { Token } from 'transliteration/domain/token'

export const line10MiddleTokens: Token[] = [
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: 'kur{d}',
    value: 'k[u]r{d!}',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: 'kur',
        value: 'k[u]r',
        name: 'kur',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'k',
            value: 'k',
            type: 'ValueToken',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: '',
            value: '[',
            side: 'LEFT',
            type: 'BrokenAway',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'BROKEN_AWAY'],
            cleanValue: 'u',
            value: 'u',
            type: 'ValueToken',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS', 'BROKEN_AWAY'],
            cleanValue: '',
            value: ']',
            side: 'RIGHT',
            type: 'BrokenAway',
          },
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'r',
            value: 'r',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '{d}',
        value: '{d!}',
        parts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'd',
            value: 'd!',
            name: 'd',
            nameParts: [
              {
                enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
                cleanValue: 'd',
                value: 'd',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: ['!'],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Determinative',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: 'KUR₂-ra',
    value: 'KUR₂!-ra',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: 'KUR₂',
        value: 'KUR₂!',
        name: 'KUR',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'KUR',
            value: 'KUR',
            type: 'ValueToken',
          },
        ],
        subIndex: 2,
        modifiers: [],
        flags: ['!'],
        sign: null,
        surrogate: [],
        type: 'Logogram',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: '-',
        value: '-',
        type: 'Joiner',
      },
      {
        enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
        cleanValue: 'ra',
        value: 'ra',
        name: 'ra',
        nameParts: [
          {
            enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
            cleanValue: 'ra',
            value: 'ra',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: ['DOCUMENT_ORIENTED_GLOSS'],
    cleanValue: '%es',
    value: '%es',
    language: 'EMESAL',
    normalized: false,
    type: 'LanguageShift',
  },
]
