import { Token } from 'transliteration/domain/token'

export const line13OpeningTokens: Token[] = [
  {
    enclosureType: [],
    cleanValue: '%sux',
    value: '%sux',
    language: 'SUMERIAN',
    normalized: false,
    type: 'LanguageShift',
  },
  {
    enclosureType: [],
    cleanValue: '|KUR₂.KUR|',
    value: '|KUR₂.KUR|',
    language: 'SUMERIAN',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '|KUR₂.KUR|',
        value: '|KUR₂.KUR|',
        type: 'CompoundGrapheme',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '{kur}ra/RA-kur₂',
    value: '{kur}ra/RA#-kur₂',
    language: 'SUMERIAN',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '{kur}',
        value: '{kur}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Determinative',
      },
      {
        enclosureType: [],
        cleanValue: 'ra/RA',
        value: 'ra/RA#',
        tokens: [
          {
            enclosureType: [],
            cleanValue: 'ra',
            value: 'ra',
            name: 'ra',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'ra',
                value: 'ra',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
          {
            enclosureType: [],
            cleanValue: 'RA',
            value: 'RA#',
            name: 'RA',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'RA',
                value: 'RA',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: ['#'],
            sign: null,
            surrogate: [],
            type: 'Logogram',
          },
        ],
        type: 'Variant',
      },
      {
        enclosureType: [],
        cleanValue: '-',
        value: '-',
        type: 'Joiner',
      },
      {
        enclosureType: [],
        cleanValue: 'kur₂',
        value: 'kur₂',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 2,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '{+kur}kur',
    value: '{+kur}kur!',
    language: 'SUMERIAN',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '{+kur}',
        value: '{+kur}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'PhoneticGloss',
      },
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur!',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: ['!'],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: ':.',
    value: ':.',
    divider: ':.',
    modifiers: [],
    flags: [],
    type: 'Divider',
  },
]
