import { Token } from 'transliteration/domain/token'

export const line12OpeningTokens: Token[] = [
  {
    enclosureType: [],
    cleanValue: 'ø',
    value: 'ø',
    type: 'WordOmitted',
  },
  {
    enclosureType: [],
    cleanValue: '($___$)',
    value: '($___$)',
    type: 'Tabulation',
  },
  {
    enclosureType: [],
    cleanValue: '($___$)',
    value: '($___$)',
    type: 'Tabulation',
  },
  {
    enclosureType: [],
    cleanValue: 'kur',
    value: 'kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '%sux',
    value: '%sux',
    language: 'SUMERIAN',
    normalized: false,
    type: 'LanguageShift',
  },
  {
    enclosureType: [],
    cleanValue: 'kur{d}',
    value: 'kur{d}',
    language: 'SUMERIAN',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: [],
        cleanValue: '{d}',
        value: '{d}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'd',
            value: 'd',
            name: 'd',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'd',
                value: 'd',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Determinative',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: 'KUR',
    value: 'KUR',
    language: 'SUMERIAN',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'KUR',
        value: 'KUR',
        name: 'KUR',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'KUR',
            value: 'KUR',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        surrogate: [],
        type: 'Logogram',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '%akk',
    value: '%akk',
    language: 'AKKADIAN',
    normalized: false,
    type: 'LanguageShift',
  },
  {
    enclosureType: [],
    cleanValue: 'kur',
    value: 'kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '%es',
    value: '%es',
    language: 'EMESAL',
    normalized: false,
    type: 'LanguageShift',
  },
]
