import { TextLine } from 'transliteration/domain/text-line'

const line11 = new TextLine({
  prefix: '1.',
  content: [
    {
      enclosureType: [],
      cleanValue: 'kur-{{kur-kur}}kur',
      value: '[(kur)]-[{{k]ur-[kur}}]k[ur]',
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: true,
      alignable: true,
      uniqueLemma: [],
      erasure: 'NONE',
      alignment: null,
      variant: null,
      parts: [
        {
          enclosureType: [],
          cleanValue: '',
          value: '[',
          side: 'LEFT',
          type: 'BrokenAway',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '',
          value: '(',
          side: 'LEFT',
          type: 'PerhapsBrokenAway',
        },
        {
          enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
          cleanValue: 'kur',
          value: 'kur',
          name: 'kur',
          nameParts: [
            {
              enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
              cleanValue: 'kur',
              value: 'kur',
              type: 'ValueToken',
            },
          ],
          subIndex: 1,
          modifiers: [],
          flags: [],
          sign: null,
          type: 'Reading',
        },
        {
          enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
          cleanValue: '',
          value: ')',
          side: 'RIGHT',
          type: 'PerhapsBrokenAway',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '',
          value: ']',
          side: 'RIGHT',
          type: 'BrokenAway',
        },
        {
          enclosureType: [],
          cleanValue: '-',
          value: '-',
          type: 'Joiner',
        },
        {
          enclosureType: [],
          cleanValue: '',
          value: '[',
          side: 'LEFT',
          type: 'BrokenAway',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '{{kur-kur}}',
          value: '{{k]ur-[kur}}',
          parts: [
            {
              enclosureType: ['BROKEN_AWAY'],
              cleanValue: 'kur',
              value: 'k]ur',
              name: 'kur',
              nameParts: [
                {
                  enclosureType: ['BROKEN_AWAY'],
                  cleanValue: 'k',
                  value: 'k',
                  type: 'ValueToken',
                },
                {
                  enclosureType: ['BROKEN_AWAY'],
                  cleanValue: '',
                  value: ']',
                  side: 'RIGHT',
                  type: 'BrokenAway',
                },
                {
                  enclosureType: [],
                  cleanValue: 'ur',
                  value: 'ur',
                  type: 'ValueToken',
                },
              ],
              subIndex: 1,
              modifiers: [],
              flags: [],
              sign: null,
              type: 'Reading',
            },
            {
              enclosureType: [],
              cleanValue: '-',
              value: '-',
              type: 'Joiner',
            },
            {
              enclosureType: [],
              cleanValue: '',
              value: '[',
              side: 'LEFT',
              type: 'BrokenAway',
            },
            {
              enclosureType: ['BROKEN_AWAY'],
              cleanValue: 'kur',
              value: 'kur',
              name: 'kur',
              nameParts: [
                {
                  enclosureType: ['BROKEN_AWAY'],
                  cleanValue: 'kur',
                  value: 'kur',
                  type: 'ValueToken',
                },
              ],
              subIndex: 1,
              modifiers: [],
              flags: [],
              sign: null,
              type: 'Reading',
            },
          ],
          type: 'LinguisticGloss',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '',
          value: ']',
          side: 'RIGHT',
          type: 'BrokenAway',
        },
        {
          enclosureType: [],
          cleanValue: 'kur',
          value: 'k[ur',
          name: 'kur',
          nameParts: [
            {
              enclosureType: [],
              cleanValue: 'k',
              value: 'k',
              type: 'ValueToken',
            },
            {
              enclosureType: [],
              cleanValue: '',
              value: '[',
              side: 'LEFT',
              type: 'BrokenAway',
            },
            {
              enclosureType: ['BROKEN_AWAY'],
              cleanValue: 'ur',
              value: 'ur',
              type: 'ValueToken',
            },
          ],
          subIndex: 1,
          modifiers: [],
          flags: [],
          sign: null,
          type: 'Reading',
        },
        {
          enclosureType: ['BROKEN_AWAY'],
          cleanValue: '',
          value: ']',
          side: 'RIGHT',
          type: 'BrokenAway',
        },
      ],
      type: 'Word',
      hasVariantAlignment: false,
      hasOmittedAlignment: false,
    },
  ],
  lineNumber: {
    number: 1,
    hasPrime: false,
    prefixModifier: null,
    suffixModifier: null,
    type: 'LineNumber',
  },
  type: 'TextLine',
})

export default line11
