import { Token } from 'transliteration/domain/token'

export const line10OpeningTokens: Token[] = [
  {
    enclosureType: [],
    cleanValue: '{d-kur₂}{d-RA}kur',
    value: '{d#-kur₂?}{d-RA!}kur',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '{d-kur₂}',
        value: '{d#-kur₂?}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'd',
            value: 'd#',
            name: 'd',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'd',
                value: 'd',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: ['#'],
            sign: null,
            type: 'Reading',
          },
          {
            enclosureType: [],
            cleanValue: '-',
            value: '-',
            type: 'Joiner',
          },
          {
            enclosureType: [],
            cleanValue: 'kur₂',
            value: 'kur₂?',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 2,
            modifiers: [],
            flags: ['?'],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Determinative',
      },
      {
        enclosureType: [],
        cleanValue: '{d-RA}',
        value: '{d-RA!}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'd',
            value: 'd',
            name: 'd',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'd',
                value: 'd',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
          {
            enclosureType: [],
            cleanValue: '-',
            value: '-',
            type: 'Joiner',
          },
          {
            enclosureType: [],
            cleanValue: 'RA',
            value: 'RA!',
            name: 'RA',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'RA',
                value: 'RA',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: ['!'],
            sign: null,
            surrogate: [],
            type: 'Logogram',
          },
        ],
        type: 'Determinative',
      },
      {
        enclosureType: [],
        cleanValue: 'kur',
        value: 'kur',
        name: 'kur',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            type: 'ValueToken',
          },
        ],
        subIndex: 1,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '{{kur}}',
    value: '{{kur}}',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: true,
    alignable: true,
    uniqueLemma: [],
    erasure: 'NONE',
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: '{{kur}}',
        value: '{{kur}}',
        parts: [
          {
            enclosureType: [],
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'LinguisticGloss',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    enclosureType: [],
    cleanValue: '',
    value: '{(',
    side: 'LEFT',
    type: 'DocumentOrientedGloss',
  },
]
