import { Token } from 'transliteration/domain/token'

export const textLineOpeningTokens: Token[] = [
  {
    enclosureType: [],
    erasure: 'NONE',
    cleanValue: 'erin₂-ŠA₂-ša₃/GIRI₃',
    value: 'erin₂-[(ŠA₂-ša₃/GIRI₃)',
    language: 'AKKADIAN',
    normalized: false,
    lemmatizable: false,
    alignable: false,
    uniqueLemma: [],
    alignment: null,
    variant: null,
    parts: [
      {
        enclosureType: [],
        cleanValue: 'erin₂',
        value: 'erin₂',
        name: 'erin',
        nameParts: [
          {
            enclosureType: [],
            cleanValue: 'erin',
            value: 'erin',
            type: 'ValueToken',
          },
        ],
        subIndex: 2,
        modifiers: [],
        flags: [],
        sign: null,
        type: 'Reading',
      },
      {
        enclosureType: [],
        cleanValue: '-',
        value: '-',
        type: 'Joiner',
      },
      {
        enclosureType: [],
        cleanValue: '',
        value: '[',
        side: 'LEFT',
        type: 'BrokenAway',
      },
      {
        enclosureType: ['BROKEN_AWAY'],
        cleanValue: '',
        value: '(',
        side: 'LEFT',
        type: 'PerhapsBrokenAway',
      },
      {
        enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
        cleanValue: 'ŠA₂',
        value: 'ŠA₂',
        name: 'ŠA',
        nameParts: [
          {
            enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
            cleanValue: 'ŠA',
            value: 'ŠA',
            type: 'ValueToken',
          },
        ],
        subIndex: 2,
        modifiers: [],
        flags: [],
        sign: null,
        surrogate: [],
        type: 'Logogram',
      },
      {
        enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
        cleanValue: '-',
        value: '-',
        type: 'Joiner',
      },
      {
        enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
        cleanValue: 'ša₃/GIRI₃',
        value: 'ša₃/GIRI₃',
        tokens: [
          {
            enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
            cleanValue: 'ša₃',
            value: 'ša₃',
            name: 'ša',
            nameParts: [
              {
                enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
                cleanValue: 'ša',
                value: 'ša',
                type: 'ValueToken',
              },
            ],
            subIndex: 3,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
          {
            enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
            cleanValue: 'GIRI₃',
            value: 'GIRI₃',
            name: 'GIRI',
            nameParts: [
              {
                enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
                cleanValue: 'GIRI',
                value: 'GIRI',
                type: 'ValueToken',
              },
            ],
            subIndex: 3,
            modifiers: [],
            flags: [],
            sign: null,
            surrogate: [],
            type: 'Logogram',
          },
        ],
        type: 'Variant',
      },
      {
        enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
        cleanValue: '',
        value: ')',
        side: 'RIGHT',
        type: 'PerhapsBrokenAway',
      },
    ],
    type: 'Word',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
]
