import { Token } from 'transliteration/domain/token'

export const akkadianWordsOpeningTokens: Token[] = [
  {
    value: '%n',
    cleanValue: '%n',
    enclosureType: [],
    erasure: 'NONE',
    language: 'AKKADIAN',
    normalized: true,
    type: 'LanguageShift',
  },
  {
    value: 'kur?',
    cleanValue: 'kur?',
    enclosureType: [],
    erasure: 'NONE',
    lemmatizable: true,
    alignable: true,
    alignment: null,
    variant: null,
    uniqueLemma: [],
    normalized: true,
    language: 'AKKADIAN',
    parts: [
      {
        value: 'kur',
        cleanValue: 'kur',
        enclosureType: [],
        erasure: 'NONE',
        type: 'ValueToken',
      },
    ],
    modifiers: ['?'],
    type: 'AkkadianWord',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    value: '<hur!>',
    cleanValue: '<hur!>',
    enclosureType: [],
    erasure: 'NONE',
    lemmatizable: true,
    alignable: true,
    alignment: null,
    variant: null,
    uniqueLemma: [],
    normalized: true,
    language: 'AKKADIAN',
    parts: [
      {
        value: '<',
        cleanValue: '',
        enclosureType: [],
        erasure: 'NONE',
        side: 'LEFT',
        type: 'Emendation',
      },
      {
        value: 'hur',
        cleanValue: 'hur',
        enclosureType: ['EMENDATION'],
        erasure: 'NONE',
        type: 'ValueToken',
      },
      {
        value: '>',
        cleanValue: '',
        enclosureType: ['EMENDATION'],
        erasure: 'NONE',
        side: 'RIGHT',
        type: 'Emendation',
      },
    ],
    modifiers: ['!'],
    type: 'AkkadianWord',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
  {
    value: '[kur-(kur)...]',
    cleanValue: '[kur-(kur)...]',
    enclosureType: [],
    erasure: 'NONE',
    lemmatizable: true,
    alignable: true,
    alignment: null,
    variant: null,
    uniqueLemma: [],
    normalized: true,
    language: 'AKKADIAN',
    parts: [
      {
        value: '[',
        cleanValue: '',
        enclosureType: [],
        erasure: 'NONE',
        side: 'LEFT',
        type: 'BrokenAway',
      },
      {
        value: 'kur',
        cleanValue: 'kur',
        enclosureType: ['BROKEN_AWAY'],
        erasure: 'NONE',
        type: 'ValueToken',
      },
      {
        value: '-',
        cleanValue: '-',
        enclosureType: ['BROKEN_AWAY'],
        erasure: 'NONE',
        type: 'Joiner',
      },
      {
        value: '(',
        cleanValue: '',
        enclosureType: ['BROKEN_AWAY'],
        erasure: 'NONE',
        side: 'LEFT',
        type: 'PerhapsBrokenAway',
      },
      {
        value: 'kur',
        cleanValue: 'kur',
        enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
        erasure: 'NONE',
        type: 'ValueToken',
      },
      {
        value: ')',
        cleanValue: '',
        enclosureType: ['BROKEN_AWAY', 'PERHAPS_BROKEN_AWAY'],
        erasure: 'NONE',
        side: 'RIGHT',
        type: 'PerhapsBrokenAway',
      },
      {
        value: '...',
        cleanValue: '...',
        enclosureType: ['BROKEN_AWAY'],
        erasure: 'NONE',
        type: 'UnknownNumberOfSigns',
      },
      {
        value: ']',
        cleanValue: '',
        enclosureType: ['BROKEN_AWAY'],
        erasure: 'NONE',
        side: 'RIGHT',
        type: 'BrokenAway',
      },
    ],
    modifiers: [],
    type: 'AkkadianWord',
    hasVariantAlignment: false,
    hasOmittedAlignment: false,
  },
]
