import { TextLine } from 'transliteration/domain/text-line'

export const greek: TextLine = new TextLine({
  prefix: 'g+1.',
  content: [
    {
      value: '%grc',
      cleanValue: '%grc',
      enclosureType: [],
      erasure: 'NONE',
      language: 'GREEK',
      normalized: false,
      type: 'LanguageShift',
    },
    {
      value: 'Α',
      cleanValue: 'Α',
      enclosureType: [],
      erasure: 'NONE',
      parts: [
        {
          value: 'Α',
          cleanValue: 'Α',
          enclosureType: [],
          erasure: 'NONE',
          letter: 'Α',
          flags: [],
          type: 'GreekLetter',
        },
      ],
      language: 'GREEK',
      normalized: false,
      lemmatizable: false,
      alignable: false,
      uniqueLemma: [],
      alignment: null,
      variant: null,
      type: 'GreekWord',
    },
  ],
  lineNumber: {
    number: 1,
    hasPrime: false,
    prefixModifier: 'g',
    suffixModifier: null,
    type: 'LineNumber',
  },
  type: 'TextLine',
})

export const akkadian: TextLine = new TextLine({
  prefix: 'g+2.',
  content: [
    {
      value: '%akkgrc',
      cleanValue: '%akkgrc',
      enclosureType: [],
      erasure: 'NONE',
      language: 'AKKADIAN',
      normalized: false,
      type: 'LanguageShift',
    },
    {
      value: '[Α#?]Α',
      cleanValue: 'ΑΑ',
      enclosureType: [],
      erasure: 'NONE',
      parts: [
        {
          value: '[',
          cleanValue: '',
          enclosureType: [],
          erasure: 'NONE',
          side: 'LEFT',
          type: 'BrokenAway',
        },
        {
          value: 'Α#?',
          cleanValue: 'Α',
          enclosureType: ['BROKEN_AWAY'],
          erasure: 'NONE',
          letter: 'Α',
          flags: ['#', '?'],
          type: 'GreekLetter',
        },
        {
          value: ']',
          cleanValue: '',
          enclosureType: ['BROKEN_AWAY'],
          erasure: 'NONE',
          side: 'RIGHT',
          type: 'BrokenAway',
        },
        {
          value: 'Α',
          cleanValue: 'Α',
          enclosureType: [],
          erasure: 'NONE',
          letter: 'Α',
          flags: [],
          type: 'GreekLetter',
        },
      ],
      language: 'AKKADIAN',
      normalized: false,
      lemmatizable: true,
      alignable: true,
      uniqueLemma: [],
      alignment: null,
      variant: null,
      type: 'GreekWord',
    },
  ],
  lineNumber: {
    number: 1,
    hasPrime: false,
    prefixModifier: 'g',
    suffixModifier: null,
    type: 'LineNumber',
  },
  type: 'TextLine',
})

export const sumerian: TextLine = new TextLine({
  prefix: 'g+3.',
  content: [
    {
      value: '%suxgrc',
      cleanValue: '%suxgrc',
      enclosureType: [],
      erasure: 'NONE',
      language: 'SUMERIAN',
      normalized: false,
      type: 'LanguageShift',
    },
    {
      value: '[Α!',
      cleanValue: 'Α',
      enclosureType: [],
      erasure: 'NONE',
      parts: [
        {
          value: '[',
          cleanValue: '',
          enclosureType: [],
          erasure: 'NONE',
          side: 'LEFT',
          type: 'BrokenAway',
        },
        {
          value: 'Α!',
          cleanValue: 'Α',
          enclosureType: ['BROKEN_AWAY'],
          erasure: 'NONE',
          letter: 'Α',
          flags: ['!'],
          type: 'GreekLetter',
        },
      ],
      language: 'SUMERIAN',
      normalized: false,
      lemmatizable: false,
      alignable: true,
      uniqueLemma: [],
      alignment: null,
      variant: null,
      type: 'GreekWord',
    },
    {
      value: 'x...]',
      cleanValue: 'x...',
      enclosureType: ['BROKEN_AWAY'],
      erasure: 'NONE',
      parts: [
        {
          value: 'x',
          cleanValue: 'x',
          enclosureType: ['BROKEN_AWAY'],
          erasure: 'NONE',
          flags: [],
          type: 'UnclearSign',
        },
        {
          value: '...',
          cleanValue: '...',
          enclosureType: ['BROKEN_AWAY'],
          erasure: 'NONE',
          type: 'UnknownNumberOfSigns',
        },
        {
          value: ']',
          cleanValue: '',
          enclosureType: ['BROKEN_AWAY'],
          erasure: 'NONE',
          side: 'RIGHT',
          type: 'BrokenAway',
        },
      ],
      language: 'SUMERIAN',
      normalized: false,
      lemmatizable: false,
      alignable: true,
      uniqueLemma: [],
      alignment: null,
      variant: null,
      type: 'GreekWord',
    },
  ],
  lineNumber: {
    number: 1,
    hasPrime: false,
    prefixModifier: 'g',
    suffixModifier: null,
    type: 'LineNumber',
  },
  type: 'TextLine',
})
