import { TextLine } from 'transliteration/domain/text-line'

export const lemmatized: TextLine[] = [
  new TextLine({
    prefix: 'l1.',
    content: [
      {
        enclosureType: [],
        erasure: 'NONE',
        cleanValue: 'kur',
        value: 'kur',
        language: 'AKKADIAN',
        normalized: false,
        lemmatizable: true,
        alignable: true,
        uniqueLemma: ['hepû I', 'hepû II'],
        alignment: null,
        variant: null,
        parts: [
          {
            enclosureType: [],
            erasure: 'NONE',
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                erasure: 'NONE',
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Word',
        hasVariantAlignment: false,
      },
      {
        enclosureType: [],
        erasure: 'NONE',
        cleanValue: '...',
        value: '...',
        type: 'UnknownNumberOfSigns',
      },
    ],
    lineNumber: {
      number: 1,
      hasPrime: false,
      prefixModifier: 'l',
      suffixModifier: null,
      type: 'LineNumber',
    },
    type: 'TextLine',
  }),
  new TextLine({
    prefix: 'l2.',
    content: [
      {
        enclosureType: [],
        erasure: 'NONE',
        cleanValue: 'kur',
        value: 'kur',
        language: 'AKKADIAN',
        normalized: false,
        lemmatizable: true,
        alignable: true,
        uniqueLemma: ['hepû I'],
        alignment: null,
        variant: null,
        parts: [
          {
            enclosureType: [],
            erasure: 'NONE',
            cleanValue: 'kur',
            value: 'kur',
            name: 'kur',
            nameParts: [
              {
                enclosureType: [],
                erasure: 'NONE',
                cleanValue: 'kur',
                value: 'kur',
                type: 'ValueToken',
              },
            ],
            subIndex: 1,
            modifiers: [],
            flags: [],
            sign: null,
            type: 'Reading',
          },
        ],
        type: 'Word',
        hasVariantAlignment: false,
      },
    ],
    lineNumber: {
      number: 2,
      hasPrime: false,
      prefixModifier: 'l',
      suffixModifier: null,
      type: 'LineNumber',
    },
    type: 'TextLine',
  }),
]
