name: Update Sitemap

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer dependencies (Ubuntu 24.04-compatible)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdrm2 \
            libgbm1 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            wget

      - name: Install script-only dependencies in isolated dir
        run: |
          mkdir tmp-script-env
          cd tmp-script-env
          npm init -y
          npm install puppeteer fs-extra --legacy-peer-deps

      - name: Run sitemap update script
        run: node scripts/updateSitemaps.js
        env:
          NODE_PATH: tmp-script-env/node_modules

      - name: Remove temporary environment
        run: rm -rf tmp-script-env

      - name: Commit sitemap changes
        id: commit
        run: |
          git config user.name "Ilya Khait"
          git config user.email "ilya.khait@lmu.de"
          git add public/sitemap
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "commit-needed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update sitemap files"
            echo "commit-needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.commit.outputs.commit-needed == 'true'
        id: create-pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SITEMAP_AUTOUPDATE }}
          commit-message: Update sitemap files
          title: 'Automated sitemap update'
          body: 'This PR was created automatically by a GitHub Action to update sitemap files.'
          base: master
          branch: autoupdate-sitemap-${{ github.run_id }}
          delete-branch: true

      - name: Enable auto-merge for PR
        if: steps.create-pull-request.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.SITEMAP_AUTOUPDATE }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
