name: Update Sitemap

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 5:00 UTC
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdrm2 \
            libgbm1 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            wget

      - name: Install script-only dependencies
        run: npm install puppeteer fs-extra --no-save --legacy-peer-deps

      - name: Run sitemap update script
        run: node scripts/update-sitemap.js