name: Update Sitemap

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer dependencies (Ubuntu 24.04-compatible)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdrm2 \
            libgbm1 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            wget

      - name: Install script-only dependencies in isolated dir
        run: |
          mkdir tmp-script-env
          cd tmp-script-env
          npm init -y
          npm install puppeteer fs-extra --legacy-peer-deps

      - name: Run sitemap update script
        run: |
          node scripts/update-sitemap.js
        env:
          NODE_PATH: tmp-script-env/node_modules

      - name: Remove temporary environment
        run: rm -rf tmp-script-env

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add public/sitemap
          git diff --cached --quiet || git commit -m "Update sitemap files"
          git push